apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: fpsoknad-mottak
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 8080
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50  
  liveness:
      path: /api/actuator/info
      initialDelay: 60
  readiness:
      path: /api/actuator/info
      initialDelay: 60  
  prometheus:
      enabled: true
      path: /api/actuator/prometheus
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50
  ingresses:
    - "https://fpsoknad-mottak.nais.preprod.local"
  resources:
      limits:
        cpu: 1500m
        memory: 3072Mi
      requests:
        cpu: 250m
        memory: 1536Mi 
  vault:
      enabled: true      
  env: 
  {{#each env}}
   - name: '{{@key}}'
     value: '{{this}}'
  {{/each}}
   - name:  varsel_hostname
     value: b27apvl176.preprod.local
   - name:  varsel_name
     value: MQ1LSC02
   - name:  varsel_port
     value: "1413"
   - name:  varsel_queuename
     value: QA.Q1_VARSELPRODUKSJON.SEND_VARSEL
   - name:  fpsoknad_varsel_kanal_queuemanager
     value: mq://b27apvl176.preprod.local:1413/MQ1LSC02
   - name:  varsel_channelname
     value: Q1_FPSOKNAD_VARSEL
   - name:  fpfordel_uri
     value: http://fpfordel.q1
   - name: fpfordel_enabled
     value: "true"
   - name:  innsyn_uri
     value: http://fpinfo.q1
   - name:  no_nav_security_oidc_issuer_selvbetjening_discoveryurl
     value: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
   - name:  spring_profiles_active
     value: preprod
