mottak:
   sender:
      domainevent:
         enabled : true
         topic : fpsoknad-mottak

management :
   endpoints:
      web:
         exposure:
            include:  '*'
   endpoint:
     health:
        show-details : always
     security:
        enabled : false
spring:
   kafka:   
      properties:
         security:
            protocol: SASL_SSL
         sasl: 
            mechanism: PLAIN
            jaas:
               config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka.username} password=${kafka.password};
      consumer: 
         bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00046.preprod.local:8443
         group-id: group_id 
         enable-auto-commit: false
         auto-offset-reset: earliest
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      producer:
         bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00046.preprod.local:8443
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
   http:
     log-request-details : true
varsel:
    username : srvappserver
    enabled : true