no.nav.security.oidc:
    issuers: selvbetjening
    issuer.selvbetjening:
      discoveryurl: SET from FASIT
      accepted_audience: Set from FASIT

info.app:
    version: '@project.version@'
    build.time:  '@timestamp@'

http.proxy : http://webproxy-nais.nav.no:8088

management:
    endpoints.web.exposure.include:  info, health, metrics, prometheus
    health:
      diskspace.enabled: false
      jms.enabled: false
server.servlet:
    context-path: /api
    use-forward-headers: true
spring:
    cache :
      cache-names : aktoer
      caffeine.spec: maximumSize=100,expireAfterAccess=3600s
    application.name : fpsoknad-oppslag
    jackson:
      default-property-inclusion: non_null
      deserialization:
         accept_single_value_as_array: true
         fail-on-unknown-properties: false
      serialization:
         fail-on-empty-beans: false
    main.banner-mode: 'off'
    metrics.web.server.auto-time-requests: true


