mottak:
   sender:
      domainevent:
         enabled : false
         topic : fpsoknad-mottak
         
no.nav:
     security.jwt.issuer.selvbetjening:
        discoveryurl: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
        cookie_name: selvbetjening-idtoken

http:
  proxy : http://webproxy-nais.nav.no:8088

info:
  app :
    version : '@project.version@'
    build:
      time : '@timestamp@'

management:
    metrics:
      web:
        server:
          auto-time-requests : true
    endpoints:
      web:
        exposure:
           include:  info, health, metrics, prometheus
    health :
      diskspace:
        enabled : false
      jms:
        enabled: false

server :
    servlet:
      context-path :  /api
    use-forward-headers: true

varsel:
    username : srvappserver
    enabled : true

spring :
    cache :
       cache-names : aktoer, organisasjon
       caffeine:
         spec: maximumSize=100,expireAfterAccess=3600s
    application:
      name : fpsoknad-mottak
    jackson :
      default-property-inclusion :  non-absent
      mapper :
         accept-case-insensitive-properties: true
      deserialization :
         accept-single-value-as-array: true
         fail-on-unknown-properties: true
      serialization :
         write-empty-json-arrays: false
         fail-on-empty-beans: false
    main:
      banner-mode : 'off'        