no.nav.security.jwt.issuer.selvbetjening.discoveryurl: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
mottak:
   sender:
      domainevent:
         enabled : true

management :
   endpoints:
      web:
         exposure:
            include:  '*'
   endpoint:
     health:
        show-details : always   
spring:
   kafka:  
       consumer: 
         bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00046.preprod.local:8443
       producer:
         bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00046.preprod.local:8443
   http:
     log-request-details : true
varsel:
    username : srvappserver
    enabled : true