version: 2.1
orbs:
  nais: navikt/nais-deployment@1.4.1
  slack: circleci/slack@3.3.0
  expiration: azihsoyn/job-expiration@0.1.0
  
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - run:
          command: |
            echo "build"
          name: build
  deploy:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - expiration/check
      - run:
          command: |
            echo "deploy"
          name: deploy
  send-approval-link:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - slack/notify:
          webhook: https://hooks.slack.com/services/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
          message: |
            Please check and approve Job to deploy.
            https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}
      - expiration/set:
          ttl: 600


workflows:
  example-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - send-approval-link:
          filters:
            branches:
              only: master
          requires:
            - build
      - pending-approval:
          filters:
            branches:
              only: master
          requires:
            - send-approval-link
          type: approval
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - pending-approval
  version: 2       
