version: 2.1
orbs:
  nais: navikt/nais-deployment@dev:issue/16-custom-tag
  slack: circleci/slack@3.3.0
  
jobs:
   build:
     working_directory: ~/fpsoknad-mottak
     docker:
       - image: circleci/openjdk:11-jdk
       
     steps:
       - checkout 
       - run : 
          name : Set environment variables
          command : echo "export RELEASE_VERSION=\"$MAJOR_VERSION-$CIRCLE_BUILD_NUM-$(git rev-parse --short HEAD)\"" >> $BASH_ENV
         
       - restore_cache: 
          name: Hente cache 
          key: fpsoknad-mottak-{{ checksum "pom.xml" }}
      
       - run:
          name: Lagre avhengigheter  
          command : mvn dependency:go-offline
      
       - save_cache:
          paths:
            - ~/.m2
          key: fpsoknad-mottak-{{ checksum "pom.xml" }}
          
       - run :
          name : Set maven versjon
          command : mvn versions:set -B -DnewVersion=$RELEASE_VERSION 
       - run: 
          name: Bygge 
          command: mvn -Dsonar.projectKey=navikt_fpsoknad-mottak -Dsonar.organization=navit -Dsonar.host.url=https://sonarcloud.io clean package sonar:sonar 
          
       - run :
          name : Revert maven versjon
          command :  mvn versions:revert

       - store_artifacts:
          path: target/surefire-reports
          
       - store_test_results:
          path: target/surefire-reports
          
       - nais/docker-deploy:
          image: navikt/$CIRCLE_PROJECT_REPONAME
          tag : $RELEASE_VERSION
          
workflows:
   version: 2
   deploy-nais:
     jobs:
      - build:
          context: NAIS deployment 
                            
      - nais/deploy:
          name: dev_deploy
          enable-vars: true
          template-vars: dev.json
          build-and-push-docker-image: false
          context: NAIS deployment
          repo: navikt/$CIRCLE_PROJECT_REPONAME
          image: navikt/$CIRCLE_PROJECT_REPONAME
          tag : $RELEASE_VERSION
          github-app-id: 20250
          nais-template: naiserator.yaml
          environment: dev-fss
          team: teamforeldrepenger
          filters:
            branches:
              only: master
          requires:
            - build
            
      - hold:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - dev_deploy 
              
      - slack/approval-notification:
           webhook: $SLACK
           message: "Godkjenn deploy til prod av $CIRCLE_PROJECT_REPONAME"
           url: https://circleci.com/workflow-run/$CIRCLE_WORKFLOW_WORKSPACE_ID
           requires:
            - dev_deploy 
                   
      - nais/deploy:
          name: prod_deploy
          enable-vars: true
          template-vars: prod.json
          build-and-push-docker-image: false
          context: NAIS deployment
          repo: navikt/$CIRCLE_PROJECT_REPONAME
          image: navikt/$CIRCLE_PROJECT_REPONAME
          tag : $RELEASE_VERSION
          github-app-id: 20250
          nais-template: naiserator.yaml
          environment: prod-fss
          team: teamforeldrepenger
          filters:
            branches:
              only: master
          requires:
            - hold      