on:
  issue_comment:
    types: [created]
jobs:
  kommenter:
     runs-on: ubuntu-latest 
     steps:
     - name: Test
       run: |
        ID=${{ github.event.comment.id }}
        echo "Dette er en test $ID"

 
