on:
  issue_comment:
    types: [created]
jobs:
  kommenter:
     runs-on: ubuntu-latest 
     steps:
     - name: Test
       run: |
        COMMAND=${{ github.event.comment.body }}
        echo " $COMMAND"

 
