on:
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/fpsoknad-mottak

jobs:
  kommenter:
    runs-on: ubuntu-latest 
    container: navikt/deployment-cli:0.4.0
    steps:
      - name: Parse
        run: |
         COMMENT=$(echo "${{ github.event.comment.body }}")
         cmd =$(echo $COMMENT | awk '{ print $1 }'`)
         echo "Kommentar er $cmd "
     
      - uses: actions/checkout@v2
      - run: git checkout d7872772f398f34b1ff180510ea985bc664a4c5f
      - name: Deploy
        run: |
          echo ::set-env name=IMAGE::docker.pkg.github.com/navikt/fpsoknad-mottak/fpsoknad-mottak:latest
      - name: Deploy til dev-fss q1
        uses: nais/deploy/actions/deploy@v1
        env:
          DRY_RUN: false
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: naiserator1.yaml
          PRINT_PAYLOAD: true
          VARS: dev.json
