on:
  issue_comment:
    types: [created]
jobs:
  kommenter:
     runs-on: ubuntu-latest 
     steps:
     - name: Test
       run: |
        COMMENT=$(echo "${{ github.event.comment.body }}")
        echo "Kommentar er ${COMMENT}"

 
