on:
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/fpsoknad-mottak

jobs:
  kommenter:
    runs-on: ubuntu-latest 
    container: navikt/deployment-cli:0.4.0
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commands: promote