on:
  issue_comment:
    types: [created]
jobs:
  kommenter:
     runs-on: ubuntu-latest 
     steps:
     - name: Test
       run: |
        BoDY=${{ github.event.comment.body }}
        echo "body er $BODY"

 
