on:
  deployment:
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
   
jobs:
  create-issue:
     runs-on: ubuntu-latest 
     steps:
     - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.deployment) }}
        run: echo "$PAYLOAD_CONTEXT"
     - name: Informer om deployment i issue
       if: github.event.deployment.environment == 'dev-fss'
       run: |
        curl --request POST \
         --url https://api.github.com/repos/${{ github.repository }}/issues \
         --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
         --header 'content-type: application/json' \
         --data '{
            "title": "Deployment til ${{ github.event.deployment.environment }}",
            "body": "Dette er mer informasjon om deploymenten (TBD)"
           }'     
 
