on:
  deployment:
jobs:
  deploy:
     runs-on: ubuntu-latest 
     steps:
     - name: Deploy
       run: |
         URL=$(echo "${{ github.event.deployment.url }}")
         echo "ur er ${URL}"
         ENV=$(echo "${{ github.event.deployment.environment }}")
         echo "nv  er ${ENV}"
         OENV=$(echo "${{ github.event.deployment.original_environment }}")
         echo "oenv er ${OENV}"
 
