name: Deploy
on:
  repository_dispatch:
    types: [deploy-command]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/fpsoknad-mottak
      
jobs:
  pong:
    runs-on: ubuntu-latest
    steps:
      - name: Set imagenavn fra args
        run:  |
              echo "::set-env name=IMAGE::$IMAGE_BASE:${{ github.event.client_payload.slash_command.arg1 }}" 
 
      - name: Deploy image
        run:  echo "Deployer {{ env.IMAGE }}" 
 
      - name: Oppdater kommentar med deployment status
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.NOTIFICATION }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            >deploy ${{ env.IMAGE }}
          reaction-type: hooray
