name: Build, push, and deploy

on:
  push:
env:
  DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/fpsoknad-mottak
         
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Bygg, tag og push
        run: |
          echo "$Bygger artifakt $(echo $GITHUB_SHA | cut -c1-7)"
          mvn --quiet clean install --batch-mode --settings .github/workflows/.m2/settings.xml -Dchangelist= -Dsha1=-$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(echo $GITHUB_SHA | cut -c1-7) 
          echo "Bygget artifakt"
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GHA }}  
      - name: Bygg og last opp Docker image
        run: |
          echo "$GITHUB_ACCESS_TOKEN" | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          echo $DOCKER_IMAGE > .docker_image
          echo "$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(echo $GITHUB_SHA | cut -c1-7)" > .docker_tag
          docker build . --pull -t $(cat .docker_image):$(cat .docker_tag)
          docker push $(cat .docker_image):$(cat .docker_tag)
          docker tag $(cat .docker_image):$(cat .docker_tag) $(cat .docker_image):latest
          docker push $(cat .docker_image):latest
          echo ::set-env name=IMAGE::$(cat .docker_image):$(cat .docker_tag)
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GHA }}
      - name: Deploy til dev-fss q1
        uses: nais/deploy/actions/deploy@v1 
        env:
          VERSION: $(cat .docker_image):$(cat .docker_tag)
          DRY_RUN: false
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: dev.json     
