name: Deployment pipeline q1

on:
  push:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/fpsoknad-mottak
  
jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
    
      - name: Sjekk ut kode
        uses: actions/checkout@v1
 
      - name: Hent Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
  
      - name: Sett opp Java 11      
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
    
      - name: Kompiler
        run: |
          echo "::set-env name=IMAGE::$IMAGE_BASE:$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(echo $GITHUB_SHA | cut -c1-7)" 
          mvn clean install --batch-mode --settings .github/workflows/.m2/settings.xml -Dchangelist= -Dsha1=-$DATO-$TAG 
 
      - name: Bygg og push docker image  
        run: |
          echo "Bygger og pusher image ${IMAGE}"
          docker build --tag ${IMAGE} .
          docker tag ${IMAGE} ${IMAGE_BASE}:latest
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE} 
          docker push ${IMAGE_BASE}:latest    
    
      - name: Deploy til dev-fss q1
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: naiserator1.yaml
          PRINT_PAYLOAD: true
          VARS: dev.json     
