name: Deploy
on:
  repository_dispatch:
    types: [deploy-command]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/fpsoknad-mottak
      
jobs:
  pong:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"
    
      - name: Set imagenavn fra args
        run:  |
              echo "::set-env name=IMAGE::$IMAGE_BASE:${{ github.event.client_payload.slash_command.arg1 }}" 
              echo "::set-env name=CLUSTER::${{ github.event.client_payload.slash_command.arg2 }}" 
       
      - name: Deploy image
        run:  echo "Deployer {{ env.IMAGE }} til {{ env.CLUSTER }}"
        
        
      - name: Sjekk ut kode
        uses: actions/checkout@v1
       
      - name: Deploy til cluster
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: naiserator1.yaml
          PRINT_PAYLOAD: true
          VARS: dev.json      
 
      - name: Oppdater kommentar med deployment status
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.NOTIFICATION }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            >deploy ${{ env.IMAGE }} til ${{ env.CLUSTER }} OK
          reaction-type: hooray
