name: Deployment pipeline q1

on:
  push:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/fpsoknad-mottak
  
jobs:
  kompiler:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v1
              
      - name: Informer om deployment i en issue som kan kommenteres for å deploye til prod
        run: |
         echo "Lager issue for ${{env.IMAGE}}"
             curl -X POST \
             https://api.github.com/repos/${{ github.repository }}/issues \
            -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "content-type: application/json" \
            --data '{
              title: Deployment OK ${{env.IMAGE}} til ${{ github.repository }},
              body: Dette er mer informasjon om deployment av ${{env.IMAGE}}
            }'  
             
      - name: Hent Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
  
      - name: Sett opp Java 11      
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
    
      - name: Kompiler
        run: | 
          echo "::set-env name=IMAGE::$IMAGE_BASE:$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(echo $GITHUB_SHA | cut -c1-7)" 
          mvn clean install --batch-mode --quiet 
                   
      - name: Bygg, tag og push Docker image  
        run: |
          echo "Bygger og pusher image ${IMAGE}"
          docker build --tag ${IMAGE} --tag ${IMAGE_BASE}:latest .
          echo  ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          docker push ${IMAGE_BASE}   
    
      - name: Deploy til dev-fss q1
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: naiserator1.yaml
          PRINT_PAYLOAD: true
          VARS: dev.json   
     