name: Slash command dispatcher
on:
  issue_comment:
    types: [created, edited]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash command dispatcher
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commands: ping
