name: ping
on:
  repository_dispatch:
    types: [ping-command]
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            >pong hello ${{ github.event.client_payload.slash_command.args }}
          reaction-type: hooray
