name: promote-command
on:
  repository_dispatch:
    types: [promote-command]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Update comment
        run: |
          curl --request POST \
           --url https://api.github.com/repos/${{ github.repository }}/issues \
           --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
           --header 'content-type: application/json' \
          --data '{
            "title": "Svar på kommentar",
            "body": "Svar er x${{ github.event.client_payload.slash_command.args }}"
          } ' 
